#ifndef RESOURCE_H
#define RESOURCE_H

#include <windows.h>

#define MAIN_DIALOG_WIDTH 190

#define IDDIALOG_MAIN_DIALOG 101
#define IDDIALOG_BAUD_RATE_SETTING 102

#define IDSTATIC_PORT 201
#define IDSTATIC_TARGET 202
#define IDSTATIC_BRS_NEW_BAUD_RATE 203

#define IDCOMBO_PORT 301

#define IDBUTTON_UPDATE_PORT_LIST 401
#define IDBUTTON_BROWSE_TARGET 402
#define IDBUTTON_SEND_MODE 403
#define IDBUTTON_RECEIVE_MODE 404
#define IDBUTTON_EXECUTE 405
#define IDBUTTON_BRS_OK 406
#define IDBUTTON_BRS_CANCEL 407

#define IDEDIT_TARGET 501
#define IDEDIT_BRS_NEW_BAUD_RATE 502

#define IDMENU_MAIN_MENU 601
#define IDMENUENTRY_BAUDRATE 602
#define IDMENUENTRY_FILE_VERSION 603
#define IDMENUENTRY_FILE_EXIT 604

#define IDSTRING_STATUSBAR_TEXT_READY 701
#define IDSTRING_STATUSBAR_TEXT_SENDING 702
#define IDSTRING_STATUSBAR_TEXT_RECEIVING 703
#define IDSTRING_MAIN_DIALOG_TITLE_SEND_MODE 704
#define IDSTRING_MAIN_DIALOG_TITLE_RECEIVE_MODE 705
#define IDSTRING_EXECUTE_BUTTON_LABEL_SEND_MODE 706
#define IDSTRING_EXECUTE_BUTTON_LABEL_RECEIVE_MODE_START 707
#define IDSTRING_EXECUTE_BUTTON_LABEL_RECEIVE_MODE_STOP 708
#define IDSTRING_TARGET_LABEL_SEND_MODE 709
#define IDSTRING_TARGET_LABEL_RECEIVE_MODE 710
#define IDSTRING_VERSION_DIALOG_TITLE 711
#define IDSTRING_VERSION_DIALOG_TEXT 712
#define IDSTRING_SFTT_VERSION 713
#define IDSTRING_SFTT_LICENCE 714
#define IDSTRING_SFTT_GITHUB 715
#define IDSTRING_ERROR_DIALOG_TITLE 716
#define IDSTRING_CANNOT_OPEN_FILE_ERROR 717
#define IDSTRING_CANNOT_GET_FILE_SIZE_ERROR 718
#define IDSTRING_CANNOT_WRITE_FILE_ERROR 719
#define IDSTRING_PORT_NOT_SPECIFIED_ERROR 720
#define IDSTRING_FILE_PATH_NOT_SPECIFIED_ERROR 721
#define IDSTRING_DESTINATION_NOT_SPECIFIED_ERROR 722
#define IDSTRING_CANNOT_OPEN_COM_PORT_ERROR 723
#define IDSTRING_CANNOT_READ_COM_PORT_ERROR 724
#define IDSTRING_CANNOT_WRITE_COM_PORT_ERROR 725
#define IDSTRING_BYTES_READ_MISMATCH_ERROR 726
#define IDSTRING_BYTES_WRITTEN_MISMATCH_ERROR 727
#define IDSTRING_SHA1_INPUT_ERROR 728
#define IDSTRING_SHA1_CALCULATION_ERROR 729
#define IDSTRING_SHA1_MISMATCH_ERROR 730
#define IDSTRING_SERIAL_START_SIGNATURE_MISMATCH_ERROR 731
#define IDSTRING_SERIAL_FINAL_SIGNATURE_MISMATCH_ERROR 732
#define IDSTRING_RECEIVE_DESTINATION_BROWSE_DIALOG_TITLE 733
#define IDSTRING_BRS_ERROR_DIALOG_TITLE 734
#define IDSTRING_BRS_BAUD_RATE_EMPTY_ERROR 735
#define IDSTRING_BRS_BAUD_RATE_OUT_OF_RANGE_ERROR 736

#endif
