#ifndef RESOURCE_H
#define RESOURCE_H

#include <windows.h>

#define MAIN_DIALOG_WIDTH 190

#define IDSTRING_PORT_SELECT_LABEL 101
#define IDSTRING_PORT_SELECT_UPDATE_BUTTON_LABEL 102

#define IDDIALOG_MAIN_DIALOG 103

#define IDCOMBO_PORT 104
#define IDBUTTON_UPDATE_PORT_LIST 105
#define IDBUTTON_BROWSE_TARGET 106
#define IDBUTTON_SEND_MODE 107
#define IDBUTTON_RECEIVE_MODE 108
#define IDBUTTON_EXECUTE 109
#define IDSTATIC_PORT 110
#define IDSTATIC_TARGET 111
#define IDEDIT_TARGET 112

#define IDMENU_MAIN_MENU 113
#define IDMENUENTRY_BAUDRATE 114
#define IDMENUENTRY_FILE_VERSION 115
#define IDMENUENTRY_FILE_EXIT 116

#define IDSTRING_STATUSBAR_TEXT_READY 117
#define IDSTRING_MAIN_DIALOG_TITLE_SEND_MODE 118
#define IDSTRING_MAIN_DIALOG_TITLE_RECEIVE_MODE 119
#define IDSTRING_EXECUTE_BUTTON_LABEL_SEND_MODE 120
#define IDSTRING_EXECUTE_BUTTON_LABEL_RECEIVE_MODE 121
#define IDSTRING_TARGET_LABEL_SEND_MODE 122
#define IDSTRING_TARGET_LABEL_RECEIVE_MODE 123
#define IDSTRING_VERSION_DIALOG_TITLE 124
#define IDSTRING_VERSION_DIALOG_TEXT 125
#define IDSTRING_SFTT_VERSION 126
#define IDSTRING_SFTT_LICENCE 127
#define IDSTRING_SFTT_GITHUB 128

#endif
