#ifndef RESOURCE_H
#define RESOURCE_H

#include <windows.h>

#define MAIN_DIALOG_WIDTH 190

#define IDSTRING_PORT_SELECT_LABEL 101
#define IDSTRING_PORT_SELECT_UPDATE_BUTTON_LABEL 102

#define IDDIALOG_MAIN_DIALOG 103

#define IDCOMBO_PORT 104
#define IDBUTTON_UPDATE_PORT_LIST 105
#define IDBUTTON_BROWSE_TARGET 106
#define IDBUTTON_SEND_MODE 107
#define IDBUTTON_RECEIVE_MODE 108
#define IDBUTTON_EXECUTE 109
#define IDSTATIC_PORT 110
#define IDSTATIC_TARGET 111
#define IDEDIT_TARGET 112

#define IDMENU_MAIN_MENU 113
#define IDMENUENTRY_BAUDRATE 114
#define IDMENUENTRY_FILE_VERSION 115
#define IDMENUENTRY_FILE_EXIT 116

#define IDSTRING_STATUSBAR_TEXT_READY 117
#define IDSTRING_STATUSBAR_TEXT_SENDING 118
#define IDSTRING_STATUSBAR_TEXT_RECEIVING 119
#define IDSTRING_MAIN_DIALOG_TITLE_SEND_MODE 120
#define IDSTRING_MAIN_DIALOG_TITLE_RECEIVE_MODE 121
#define IDSTRING_EXECUTE_BUTTON_LABEL_SEND_MODE 122
#define IDSTRING_EXECUTE_BUTTON_LABEL_RECEIVE_MODE_START 123
#define IDSTRING_EXECUTE_BUTTON_LABEL_RECEIVE_MODE_STOP 124
#define IDSTRING_TARGET_LABEL_SEND_MODE 125
#define IDSTRING_TARGET_LABEL_RECEIVE_MODE 126
#define IDSTRING_VERSION_DIALOG_TITLE 127
#define IDSTRING_VERSION_DIALOG_TEXT 128
#define IDSTRING_SFTT_VERSION 129
#define IDSTRING_SFTT_LICENCE 130
#define IDSTRING_SFTT_GITHUB 131
#define IDSTRING_ERROR_DIALOG_TITLE 132
#define IDSTRING_CANNOT_OPEN_FILE_ERROR 133
#define IDSTRING_CANNOT_GET_FILE_SIZE_ERROR 134
#define IDSTRING_CANNOT_WRITE_FILE_ERROR 135
#define IDSTRING_PORT_NOT_SPECIFIED_ERROR 136
#define IDSTRING_FILE_PATH_NOT_SPECIFIED_ERROR 137
#define IDSTRING_DESTINATION_NOT_SPECIFIED_ERROR 138
#define IDSTRING_CANNOT_OPEN_COM_PORT_ERROR 139
#define IDSTRING_CANNOT_READ_COM_PORT_ERROR 140
#define IDSTRING_CANNOT_WRITE_COM_PORT_ERROR 141
#define IDSTRING_BYTES_READ_MISMATCH_ERROR 142
#define IDSTRING_BYTES_WRITTEN_MISMATCH_ERROR 143
#define IDSTRING_SHA1_INPUT_ERROR 144
#define IDSTRING_SHA1_CALCULATION_ERROR 145
#define IDSTRING_SHA1_MISMATCH_ERROR 146
#define IDSTRING_SERIAL_START_SIGNATURE_MISMATCH_ERROR 147
#define IDSTRING_SERIAL_FINAL_SIGNATURE_MISMATCH_ERROR 148
#define IDSTRING_RECEIVE_DESTINATION_BROWSE_DIALOG_TITLE 149

#endif
